### ISSUE TITLE
Keys get stuck when window focus is lost

### ISSUE THREAD

**Issue by eioo** [mattbruv/Lentokonepeli#19]
To reproduce:

1. Hold CTRL (shoot) down
2. Click outside browser window
3. Plane is on auto-fire mode

Same issue with other keys too.

**Comment by APN-Pucky** [comment]
Yes, currently we only send changes of input to the server. 
Best solution is probably to check on the client side when the browser is left and then send a no input signal.

**Comment by mattbruv** [comment]
Closing this as I am remaking the codebase
